### ISSUE TITLE
re-name `lg-bot` to echo

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/product-development#87]
## Tasks
- [x] rename local constant `BOT_USERNAME` in rocketchat-lg-sso to exported global `LG_BOT_USERNAME`
- [x] use `LG_BOT_USERNAME` global in rocketchat-lg-slash-commands
- [x] update Mongo in production to change `lg-bot` to `echo`
- [x] upload elephant avatar for `echo` to production
- [x] deploy new version of Rocket.Chat to production with updated rocketchat-lg-\* packages
## Background

It'd be nice if we had an anthropomorphized character that players engaged with, something with more depth and personality than `lg-bot`.

@shereefb you mentioned having done some thinking about this already, but I wasn't sure if that work was captured anywhere.
